// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5y7-EKOC_jkZqyUD1ixi3IKwH-GSjmUw',
    appId: '1:927063133007:web:b76d080cd8ce39c9e9533a',
    messagingSenderId: '927063133007',
    projectId: 'shoppinglist-a22c1',
    authDomain: 'shoppinglist-a22c1.firebaseapp.com',
    storageBucket: 'shoppinglist-a22c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNaz_KMfnOTkdneaXCyu1kG9vOAU5qyaY',
    appId: '1:927063133007:android:e88ce0f586a38c43e9533a',
    messagingSenderId: '927063133007',
    projectId: 'shoppinglist-a22c1',
    storageBucket: 'shoppinglist-a22c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4WOXKh_4UXsbVEhTJ8eqI9MtMhdG7qxM',
    appId: '1:927063133007:ios:25042224408d4b25e9533a',
    messagingSenderId: '927063133007',
    projectId: 'shoppinglist-a22c1',
    storageBucket: 'shoppinglist-a22c1.firebasestorage.app',
    iosBundleId: 'com.example.twoplayercrossword',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4WOXKh_4UXsbVEhTJ8eqI9MtMhdG7qxM',
    appId: '1:927063133007:ios:25042224408d4b25e9533a',
    messagingSenderId: '927063133007',
    projectId: 'shoppinglist-a22c1',
    storageBucket: 'shoppinglist-a22c1.firebasestorage.app',
    iosBundleId: 'com.example.twoplayercrossword',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5y7-EKOC_jkZqyUD1ixi3IKwH-GSjmUw',
    appId: '1:927063133007:web:5216d86a74810e56e9533a',
    messagingSenderId: '927063133007',
    projectId: 'shoppinglist-a22c1',
    authDomain: 'shoppinglist-a22c1.firebaseapp.com',
    storageBucket: 'shoppinglist-a22c1.firebasestorage.app',
  );
}
